export { ArticleLayout } from "./ArticleLayout"
export { getEntryContentLayout } from "./factory"
export { PicturesLayout } from "./PicturesLayout"
export { SocialMediaLayout } from "./SocialMediaLayout"
export { VideosLayout } from "./VideosLayout"
