export const RSSHubCategories = [
  "all",
  "social-media",
  "new-media",
  "traditional-media",
  "bbs",
  "blog",
  "programming",
  "design",
  "live",
  "multimedia",
  "picture",
  "anime",
  "program-update",
  // "university",
  // "forecast",
  // "travel",
  "shopping",
  "game",
  "reading",
  // "government",
  // "study",
  "journal",
  "finance",
] as const

export type RSSHubCategory = (typeof RSSHubCategories)[number]

export const CategoryMap: Record<RSSHubCategory, { color: string; emoji: string }> = {
  all: { color: "#FFCA28", emoji: "⭐️" },
  "social-media": { color: "#42A5F5", emoji: "💬" },
  "new-media": { color: "#FF7043", emoji: "📣" },
  "traditional-media": { color: "#BDBDBD", emoji: "📰" },
  bbs: { color: "#FFB74D", emoji: "💭" },
  blog: { color: "#AB47BC", emoji: "✍️" },
  programming: { color: "#66BB6A", emoji: "💻" },
  design: { color: "#EC407A", emoji: "🎨" },
  live: { color: "#EF5350", emoji: "📺" },
  multimedia: { color: "#FF8A65", emoji: "🎞️" },
  picture: { color: "#26A69A", emoji: "🖼️" },
  anime: { color: "#F06292", emoji: "🌸" },
  "program-update": { color: "#78909C", emoji: "🔄" },
  // university: { color: "#5C6BC0", emoji: "🎓" },
  // forecast: { color: "#4FC3F7", emoji: "⛅️" },
  // travel: { color: "#4DD0E1", emoji: "✈️" },
  shopping: { color: "#EEAE24", emoji: "🛍️" },
  game: { color: "#7E57C2", emoji: "🎮" },
  reading: { color: "#3F8BB7", emoji: "📖" },
  // government: { color: "#90A4AE", emoji: "🏛️" },
  // study: { color: "#FFD54F", emoji: "📚" },
  journal: { color: "#A1887F", emoji: "📓" },
  finance: { color: "#81C784", emoji: "💰" },
}
